### ISSUE TITLE
Do one thing and do it well

### ISSUE THREAD

**Issue by mudrd8mz** [cwarwicker/moodle-local_utils#4]
I generally like the good old UNIX philosophy "do one thing and do it well" and I saw that Moodle plugins that follow it, are generally successful too.

I am not sure it is wise to try and have one general plugin with various development utilities (eventually added in the future).

Instead of this "local_utils" doing two or three (eventually) unrelated things, why not to simply convert the current functionality into something like a well focused administration tool like `tool_ribbons` that would allow to do just these ribbons and nothing else.

Not only developers may find such feature useful.

**Comment by cwarwicker** [comment]
Ok. I did think it might be better to do that, after I'd submitted it.
